### ISSUE TITLE
Pancakeswap Sniping bot

### ISSUE THREAD

**Issue by a180024** [sszczep/UniswapSniperBot#1]
Would be nice if there's one for PCS too thanks!

**Comment by sszczep** [comment]
WIP. Will keep you updated.

**Comment by scheta1** [comment]
hey bro, can i get your telegram or any contact

**Comment by scheta1** [comment]
the new one pcs is not working on me bro
can u help me?

**Comment by sszczep** [comment]
PCS is not supported. As the Bloxroute pricing plan has changed recently, I have no way to maintain this project anymore. I will still provide help with installing and configuration, however don't expect any new futures coming anytime soon. Feel free to create forks and pull requests. Please use GitHub issues and do not write to me directly as I might not answer.
